config/routes.rb
Rails.application.routes.draw do
  resources :users
  get "/user", to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"
  resources :articles
  # get "/articles", to: "articles#index"

  
end   

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
    article1 = Article.new
    article1 = Article.find_by(title: @article.title);
    puts article1.to_json
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      # render js: "alert('Update Success')"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
        if @user.save
            UserMailer.with(user: @user).welcome_email.deliver_now

            format.html { redirect_to(@user, notice: 'ユーザーが正常に作成されました') }
            format.json { render json: @user, status: :created, location: @user }
        else
            format.html { render action: 'new'}
            format.json { render json: @user.errors, status: :unprocessable_entity }
        end

    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
        params.require(:user).permit(:email, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% @article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <% @article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Article編集テスト </h1>
<%= render "form", articles: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<br>
<%= link_to "新規作成", new_article_path %>
<table>
    <tr> 
        <th> タイトル </th>
        <th> メッセージ </th>
        <th colspan="2"> Action </th>
    </tr>
    <% @articles.each do |article| %>
        <tr>
            <td> <%= article.title %> </td> 
            <td> <%= article.body  %> </td>
            <td> <%= link_to '編集', edit_article_path(article), class: "btn btn-edit" %> </td>
            <td> <%= link_to '削除', article_path(article), data: {
                turbo_method: :delete,
                turbo_confirm: "削除してもよろしいですか？"
            } %> </td>
        </tr>
    <% end %>
</table>

<style>
    table {
        border-collapse: collapse
    }
    table tr {
        border: 1px solid black;
    }
    table td, table th {
        border-right: 1px solid black;
    }
    .btn-edit {
        width: auto;
        height: auto;
    }
</style>

app/views/articles/new.html.erb
<h1>新規Article作成 </h1>
<%= render "form", articles: @article %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
    <div>
        <%= form.label :email %><br>
        <%= form.text_field :email %>
        <% @user.errors.full_messages_for(:email).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% @user.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<%= link_to "New user", new_user_path %>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user registration </h1>
<%= render "form", users: @user %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>